name: Update changelog
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: 'Needs to match, exactly, the name of a milestone. The version to be released please respect: major.minor.patch or major.minor.patch-beta<number> format. example: 7.4.3 or 7.4.3-beta1'
      skip_pr:
        required: false
        default: "0"
      skip_community_post:
        required: false
        default: "0"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Run update changelog (manually invoked)
        uses: grafana/grafana-github-actions-go/update-changelog@main
        with:
          token: ${{ secrets.GH_BOT_ACCESS_TOKEN }}
          version: ${{ inputs.version }}
          metrics_api_key: ${{ secrets.GRAFANA_MISC_STATS_API_KEY }}
          community_api_key: ${{ secrets.GRAFANABOT_FORUM_KEY }}
          community_api_username: grafanabot
          skip_pr: ${{ inputs.skip_pr }}
          skip_community_post: ${{ inputs.skip_community_post }}
